# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Secure Prescriptive Analytics
title_tail: " - Secure Prescriptive Analytics"
email: michael.affenzeller@fh-ooe.at
description: #>- # this means to ignore newlines until "baseurl:"
  de: Das Forschungsprojekt Secure Prescriptive Analytics setzt sich zum Ziel das durch die Kombination von Modellierung und Simulation, Optimierung, Interpretable und Privacy-Preserving Machine Learning entstehende Potential zu heben.
  en: The research project Secure Prescriptive Analytics aims to leverage the potential of combining modeling and simulation, optimization, interpretable and privacy-preserving machine learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.prescriptiveanalytics.at" # the base hostname & protocol for your site, e.g. http://example.com
lang: de
author: Secure Prescriptive Analytics
keywords: modeling and simulation, optimization, interpretable machine learning, privacy-preserving machine learning, surrogate modeling
# twitter_username: spa
# github_username:  spa

# SEO
google_analytics: false

# Build settings
# markdown: kramdown
# highlighter: rouge
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-gist


environment: development
regenerate: false

show_drafts: false
future: false

blogname: "blog"
#permalink: blog/:title
permalink: blog/:year/:title/
#permalink: blog/:categories/:year/:month/:day/:title
paginate: 7
paginate_path: "blog/page:num/"

collections:
  category:
    output: true
    permalink: /blog/:name/

defaults:
  - 
    scope:
      path: ""
      type: "category"
    values:
      layout: "category"
  -
    scope:
      path: "assets/img"
    values:
      image: true


excerpt_separator: <!--more-->

# Server Config options
livereload: false
reload_port: 5678

sass:
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# exclude:
#   - Gemfile
#   - Gemfile.lock
